name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -q oneUI-v6.zip -d src
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.5.0
      - name: 构建
        run: |
          D="$(dirname "$(find src -name settings.gradle.kts | head -1)")"
          cd "$D"
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          gradle assembleDebug --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: src/**/build/outputs/apk/**/*.apk
